### ISSUE TITLE
Tracking mdn/data deprecation

### ISSUE THREAD

**Issue by Rumyra** [mdn/content-team-projects#43]
- [ ] Research cssinfo
- [ ] Can we remove cssinfo?
- [ ] Add a note to the readme to say this isn't being maintained and here are alternatives
- [ ] Reach to partners to say if we stop maintaining this will you be ok - here's alternatives
- [ ] Add a note to npm package saying this isn't maintained - with a timeline for stopping releasing
- [ ] Archive in 12 months(?) and stop releasing

**Comment by schalkneethling** [comment]
What is the status of the `cssinfo` macro now that the `webref` pull request has landed?

**Comment by schalkneethling** [comment]
If I look at the weekly downloads for `mdn-data`(19 467 360) and `csstree`(19 986 685) I would bet that `csstree` makes up at least 90% of the weekly download shown for `mdn-data`. I have reached out to one of the maintainers of the `cssinfo` package to understand whether `webref` would be an option for them.

**Comment by Rumyra** [comment]
So the pull request was to replace `csssyntax` we still need to figure out what to do with `cssinfo` (it's _our_ last remaining macro that uses mdn/data)

Great to reach out to `csstree` to find out how they are using data 👍 that's a good first step - I wonder if we can put a note on the data package to get in touch if you're depending on this because we'd like to know more about how it's being used

**Comment by schalkneethling** [comment]
> I wonder if we can put a note on the data package to get in touch if you're depending on this because we'd like to know more about how it's being used

That is a really good idea actually. 🎉
