### ISSUE TITLE
[Repo] todo-notifications

### ISSUE THREAD

**Issue by schalkneethling** [mdn/content-team-projects#81]
What to do with https://github.com/mdn/to-do-notifications

- [ ] triage prs
- [ ] triage issues
- [ ] add contribution doc
- [ ] add any notes about repo to readme
- [ ] change master to main
- [ ] move if necessary - create new folder
- [ ] update urls in content
- [ ] archive repo if necessary
- [ ] add to motherboard project

**Comment by schalkneethling** [comment]
@Rumyra Thoughts on this one?

**Comment by Rumyra** [comment]
Looks like this one is for dom-examples https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API 👍
